%MATPOWER_ADDPATH

%% add MATPOWER paths
addpath( ...
    'matpower7.0\lib', ...
    'matpower7.0\lib\t', ...
    'matpower7.0\mips\lib', ...
    'matpower7.0\mips\lib\t', ...
    'matpower7.0\most\lib', ...
    'matpower7.0\most\lib\t', ...
    'matpower7.0\mptest\lib', ...
    'matpower7.0\mptest\lib\t', ...
    'matpower7.0\extras\maxloadlim', ...
    'matpower7.0\extras\maxloadlim\tests', ...
    'matpower7.0\extras\maxloadlim\examples', ...
    'matpower7.0\extras\misc', ...
    'matpower7.0\extras\reduction', ...
    'matpower7.0\extras\sdp_pf', ...
    'matpower7.0\extras\se', ...
    'matpower7.0\extras\smartmarket', ...
    'matpower7.0\extras\state_estimator', ...
    'matpower7.0\extras\syngrid\lib', ...
    'matpower7.0\extras\syngrid\lib\t', ...
    '-end' );
